#+latex_class: cn-article
#+title: Android Study Plan
#+author: deepwaterooo

* Daily updates
- 因为需要准备一个面试，这几天不更新算法系列，只准备安卓面试
- win 10 wsl 1 ubuntu 18 adb configuration done, not complicated, once search for solutions, and config, it works.
- api levle 30 androidx basic project environment can be configured, but dynamic fragment add not done yet, switched back to api 28 temporatorily
- wsl 1 ubuntu 18 adb logcat is so slow. after 9pm yesterday, 150K lines of log, I could only adb logcat previous project samplefragments, can can not grab any FirstFragment nor Second Fragment Log.i info. may switch laptop back to Mac, but it has only 8GB memory, and internet too slow for that laptop
- today will review major components, as well small details, notes summaries to move on
- *恶鬼们昨天晚上今天早上又疯狂作案一晚，一个故意晚回来，用洗手间，用厨房，半夜一两点钟还在故意厨房里开厨导柜吵别人；一个今天早上五点钟便受恶房东指挥，故意开车库噪音极大的声响，早上 五点钟便故意吵醒别人休息，实在是无恶不作*

* 系统服务篇
:clock1: DONE: Android 如何启动？
[x] DONE: Android 应用进程启动流程
[ ] 什么是系统服务？
[ ] ActivityManagerService
[ ] SystemServer
[x] DONE: Android 应用安装过程源码解析
[ ] WindowManagerService
[ ] Zoyote 前世今生

* 通信框架篇
[x] Binder 完全解析
[x] DONE: Binder 完全解析（一）概述
[x] DONE: Binder 完全解析（二）设计详解
[x] DONE: Binder 完全解析（三）AIDL实现原理分析
[x] Handler 通信框架
[x] DONE: Handler消息机制源码解析

* 应用组件篇
[ ] Application 是什么？
DONE: Context 分析
[ ] Activity 组件分析
[x] DONE: Activity生命周期是如何实现的
[ ] Services 组件分析
[ ] ContentProvider 组件分析
[ ] Broadcast 组件分析

* 珠玑拾遗
[ ] Gradle 用法
[ ] 混淆一二事

Andriod系统开发

* Android操作系统概述
Android平台介绍；Android平台特性；Android平台架构；Android Navtive C/C++程序开发；Android NDK；Native开发方式与JAVA开发方式比较。
* Android开发环境搭建
Android SDK介绍；Eclipse ADT插件；Android模拟器开发。
* Android项目结构分析
资源管理(Resources)分析；drawable分析；layout分析；Activity分析；Intent分析；Service分析；Content分析。
* Android UI设计
标准控件的使用；设计开发自定义控件；Layout布局的使用；触摸/按键（UI Events）事件处理方法；View，SurfaceView，Canvas,Paint类分析使用；显示文本以及显示特殊效果文本；绘图及显示图片；实现动画效果。
* Intent Receive
Intent的作用和目的；属性讲解；Android定义解析Intent；AndroidManifest.xml深入分析。
* Service
什么是Service，如何使用Service，Service的生命周期，BroadcastReceiver的使用。
* Content Provider
SQLite介绍，创建Content Providers，使用Content Providers，使用URI语法进行增删改查。
* Android高级应用开发
访问本地通讯录；网络连接的相关知识；流媒体的处理；URLConnection和HttpURLConnection的应用；
HttpClient的分析；本地文件浏览管理；音视频播放处理；Widget应用开发。
* Android程序发布部署建
Android 调试桥；启用logcat日志调试；模拟器上安装删除软件；打包* 签名和安装软件到设备。
* Android 底层架构分析
移植Android到新的硬件平台；需要支持Linux 操作系统的硬件平台架构分析；支持Android的Linux内核特性分析；为Linux内核增加Android特性；移植Android Debug Bridge调试接口；编写／移植Android内核驱动；硬件支持double frame buffer/page flipping；bionic库移植与优化；Dalvik Vm移植；第三方应用程序移植；建立Android移植开发平台；新的嵌入式处理器引入的Android相关问题；获得高效的Android工具链。
* Android移植
支持ARM11的Linux-2.6.28内核新特性简介；移植LCD double buffer驱动；移植触摸屏驱动；移植Android键盘驱动；移植Wifi驱动支持Android上网功能；移植电源管理驱动，支持Android电池管理；部署Android系统到实际ARM11平台。
* 阶段项目实战与测试
通过对ITelephony接口和ISms接口以及AIDL在Android程序中的开发应用，开发一个打电话和发短信的程序。

* 自定义view Android 11 api level android M 
** gradle.properties
#+BEGIN_SRC xm
android.useAndroidX=true
landroid.enableJetifier=true
#+END_SRC
- 什么是Jetifier？ 例如，要使用androidx打包的依赖项创建新项目，此新项目需要在gradle.properties文件中添加以下行：

java version 8
 compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

import android.os.Bundle;
import android.support.design.widget.FloatingActionButton;
import android.support.design.widget.Snackbar;
import android.view.View;
import android.view.Menu;
import android.view.MenuItem;
import androidx.appcompat.app.AppCompatActivity;
import androidx.appcompat.widget.Toolbar;
import com.google.android.material.floatingactionbutton.FloatingActionButton;
import com.google.android.material.snackbar.Snackbar;

    <com.me.generalprac.CustomTitleView
        android:layout_width="match_parent"
        android:layout_height="wrap_content"/>
    <include layout="@layout/custom_title"/>

